---
- hosts: tag_Name_worker2
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
  # Update the Repository
  - name: Update apt packages
    apt:
      update_cache: yes
  # Add the GPG key for Docker
  - name: Add the GPG key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  # Add docker Repo
  - name: Add docker Repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
      update_cache: yes
  # Add the GPG key for kubernetes
  - name: Add the GPG key for kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  # Add the kubernetes repository
  - name: Add the kubernetes repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'
  # Update the Repository
  - name: Update the Repository
    apt:
      update_cache: yes
  # Install Docker and Kubernetes packages.
  - name: Install Docker and Kubernetes packages
    shell: sudo apt-get install -y docker-ce=5:20.10.7~3-0~ubuntu-$(lsb_release -cs) kubelet=1.21.1-00 kubeadm=1.21.1-00 kubectl=1.21.1-00
  # To hold the versions so that the versions will not get accidently upgraded.
  - name: To hold the versions so that the versions will not get accidently upgraded
    shell: sudo apt-mark hold docker-ce kubelet kubeadm kubectl
  # Start and enable Docker Services
  - name: Start and enable Docker Services
    shell: |
     sudo systemctl restart docker
     sudo systemctl enable docker
  # Disable Swap
  - name: Disabling Swap on all nodes
    shell: sudo swapoff -a
  # Enable the iptables bridge(Set a value in the sysctl file , to allow proper network settings for Kubernetes on all the servers)
  - name: Enable the iptables bridge
    shell: |
     echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf
     sudo sysctl -p
  # Removing container Runtime Error
  - name: Remove config.toml and Restart Containerd
    shell: |
     sudo rm -rf /etc/containerd/config.toml
     sudo systemctl restart containerd
  # Joining the Worker nodes to the cluster
  - name: join cluster
    shell: "{{ hostvars['master.example.com'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
    args:
     chdir: $HOME
     creates: node_joined.txt